server:
  port: 8081

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/hms
    username: hospital
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true

